##===- projects/parpot/lib/DynCallGraph/Makefile -----------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL=../..
LIBRARYNAME = parpot_dyncallgraphreader
BUILD_ARCHIVE = 1
SHARED_LIBRARY = 1

include $(LEVEL)/Makefile.common

