##===- projects/parpot/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=Analysis DebugInfo Instrumentation DynCallGraph Test

include $(LEVEL)/Makefile.common